SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

USE mydb;

ALTER TABLE categories
  ADD PRIMARY KEY (CategoryID);

ALTER TABLE customers
  ADD PRIMARY KEY (CustomerID);

ALTER TABLE employees
  ADD PRIMARY KEY (EmployeeID);

ALTER TABLE orders
  ADD PRIMARY KEY (OrderID),
  ADD KEY CustomerID (CustomerID),
  ADD KEY EmployeeID (EmployeeID),
  ADD KEY ShipperID (ShipperID);

ALTER TABLE order_details
  ADD PRIMARY KEY (OrderDetailID),
  ADD KEY OrderID (OrderID),
  ADD KEY ProductID (ProductID);

ALTER TABLE products
  ADD PRIMARY KEY (ProductID),
  ADD KEY CategoryID (CategoryID),
  ADD KEY SupplierID (SupplierID);

ALTER TABLE shippers
  ADD PRIMARY KEY (ShipperID);

ALTER TABLE suppliers
  ADD PRIMARY KEY (SupplierID);


ALTER TABLE categories
  MODIFY CategoryID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

ALTER TABLE customers
  MODIFY CustomerID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=92;

ALTER TABLE employees
  MODIFY EmployeeID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

ALTER TABLE orders
  MODIFY OrderID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10444;

ALTER TABLE order_details
  MODIFY OrderDetailID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=519;

ALTER TABLE products
  MODIFY ProductID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;

ALTER TABLE shippers
  MODIFY ShipperID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

ALTER TABLE suppliers
  MODIFY SupplierID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;


ALTER TABLE orders
  ADD CONSTRAINT orders_ibfk_1 FOREIGN KEY (CustomerID) REFERENCES customers (CustomerID),
  ADD CONSTRAINT orders_ibfk_2 FOREIGN KEY (EmployeeID) REFERENCES employees (EmployeeID),
  ADD CONSTRAINT orders_ibfk_3 FOREIGN KEY (ShipperID) REFERENCES shippers (ShipperID);

ALTER TABLE order_details
  ADD CONSTRAINT order_details_ibfk_1 FOREIGN KEY (OrderID) REFERENCES orders (OrderID),
  ADD CONSTRAINT order_details_ibfk_2 FOREIGN KEY (ProductID) REFERENCES products (ProductID);

ALTER TABLE products
  ADD CONSTRAINT products_ibfk_1 FOREIGN KEY (CategoryID) REFERENCES categories (CategoryID),
  ADD CONSTRAINT products_ibfk_2 FOREIGN KEY (SupplierID) REFERENCES suppliers (SupplierID);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
